framework:
    messenger:
        transports:
            NumberCreationRequestAPI.NumberService: "%env(NumberCreationRequestAPI_NumberService)%"
            NumberChangeStateRequestAPI.NumberService: "%env(NumberChangeStateRequestAPI_NumberService)%"
            NumberListAPI.ServiceStatus: "%env(NumberListAPI_ServiceStatus)%"
            NumberListAPI.Labor: "%env(NumberListAPI_Labor)%"
            NumberListAPI.TestCentrum: "%env(NumberListAPI_TestCentrum)%"

        routing:
            'MessageInfo\NumberCreationRequestAPIDataProvider':
                - NumberCreationRequestAPI.NumberService

            'MessageInfo\NumberChangeStateRequestAPIDataProvider':
                - NumberChangeStateRequestAPI.NumberService

            'MessageInfo\NumberListAPIDataProvider':
                - NumberListAPI.ServiceStatus
                - NumberListAPI.Labor
                - NumberListAPI.TestCentrum
