framework:
    messenger:
        transports:
            test_event.test_event: "%env(TEST_EVENT_TEST_EVENT)%"

        routing:
            'MessageInfo\NumberCreationRequestAPIDataProvider' : test_event.test_event
