version: '3'

services:
    redis:
        image: redis:3.2.11
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
    redisui:
        image: tenstartups/redis-commander
        command: --redis-host redis
        links:
            - redis:redis
        ports:
            - "8081:8081"
    rabbitmq:
        image: rabbitmq:3.7.6-management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15672:15672
            - 5672:5672
